name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: dependencies Install
        run: |
          cd app
          npm cache clean --force
          npm install --registry=https://registry.npmmirror.com


      - name: Install Dependencies
        run: npm ci

      - name: Static Code Analysis
        uses: returntocorp/semgrep-action@v1

      - name: Build Docker Image
        run: docker build -t myapp:latest ./app

      - name: Scan Docker Image
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL myapp:latest

      - name: Push if Passed
        if: success()
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push myapp:latest
